export const STOPWORDS = new Set(
  `a an the and or but if then than this that these those with without within into onto from for of to in on at by as is are was were be been being have has had do does did will would shall should can could may might must not no nor so such own same other more most some any all each few many our your their his her its we you they he she it i me us them my mine ours yours role roles team teams work working works ability strong excellent good great proven plus etc using used use across over under about per via you'll we're you're including include includes required require requirements responsibilities responsible looking ideal candidate candidates experience experiences year years month months day days new help helps build building built make makes made join joining company companies position opportunity opportunities skill skills knowledge understanding ensure ensuring deliver delivering develop developing development developer engineer engineers`
    .split(/\s+/)
    .filter(Boolean),
);

export const KNOWN_SKILLS = [
  "javascript",
  "typescript",
  "react",
  "react native",
  "next.js",
  "nextjs",
  "angular",
  "vue",
  "svelte",
  "redux",
  "node.js",
  "nodejs",
  "express",
  "graphql",
  "rest",
  "php",
  "python",
  "java",
  "golang",
  "rust",
  "c++",
  "html",
  "css",
  "sass",
  "tailwind",
  "bootstrap",
  "webpack",
  "vite",
  "jest",
  "cypress",
  "playwright",
  "testing library",
  "mongodb",
  "mysql",
  "postgresql",
  "redis",
  "firebase",
  "aws",
  "azure",
  "gcp",
  "docker",
  "kubernetes",
  "ci/cd",
  "git",
  "github",
  "gitlab",
  "agile",
  "scrum",
  "figma",
  "accessibility",
  "responsive",
  "performance",
  "microservices",
  "websocket",
  "three.js",
  "webgl",
  "machine learning",
  "power bi",
  "sql",
  "nosql",
];
